name: Publish Python Package

on:
  push:
    branches:
      - main          # Trigger on pushes to the main branch
    tags:
      - 'v*'           # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Specify the Python version you're using

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    # Step 4: Build the package (source distribution and wheel)
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    # Step 5: Publish to PyPI
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__  # Use __token__ for authentication
        password: ${{ secrets.PYPI_API_TOKEN }}  # Securely use the token stored in GitHub Secrets
